export interface Job {
  id: string;
  title: string;
  company: string;
  companyType: string;
  location: string;
  country: string;
  salary: string;
  experience: string;
  contractDuration: string;
  description: string;
  responsibilities: string[];
  requirements: string[];
  skills: string[];
  benefits: string[];
  postedDate: string;
}

export interface Testimonial {
  id: string;
  name: string;
  role: string;
  company?: string;
  country: string;
  image?: string;
  quote: string;
  type: 'candidate' | 'company';
}

export interface TrustStat {
  id: string;
  value: string;
  label: string;
  icon: string;
}

export const trustStats: TrustStat[] = [
  {
    id: '1',
    value: '500+',
    label: 'Successful Placements',
    icon: 'Users',
  },
  {
    id: '2',
    value: '95%',
    label: 'Visa Success Rate',
    icon: 'Award',
  },
  {
    id: '3',
    value: '50+',
    label: 'Partner Companies',
    icon: 'Briefcase',
  },
  {
    id: '4',
    value: '18+',
    label: 'Years Experience',
    icon: 'Star',
  },
];

export const jobs: Job[] = [
  {
    id: '1',
    title: 'Software Engineer',
    company: 'Tech Solutions Bulgaria',
    companyType: 'Technology',
    location: 'Sofia',
    country: 'Bulgaria',
    salary: '€2,500 - €3,500/month',
    experience: '2-5 years',
    contractDuration: '24 months',
    description: 'Join our dynamic team as a Software Engineer in Sofia. We are looking for passionate developers to work on cutting-edge projects.',
    responsibilities: [
      'Design and develop scalable web applications',
      'Collaborate with cross-functional teams',
      'Write clean, maintainable code',
      'Participate in code reviews',
      'Debug and resolve technical issues',
    ],
    requirements: [
      'Bachelor\'s degree in Computer Science or related field',
      '2+ years of professional software development experience',
      'Strong proficiency in JavaScript, TypeScript, and React',
      'Experience with Node.js and databases',
      'Excellent problem-solving skills',
    ],
    skills: ['JavaScript', 'TypeScript', 'React', 'Node.js', 'SQL'],
    benefits: ['Health insurance', 'Relocation support', 'Professional development', 'Flexible hours'],
    postedDate: '2024-12-01',
  },
  {
    id: '2',
    title: 'Business Development Manager',
    company: 'Global Trade Serbia',
    companyType: 'Business Services',
    location: 'Belgrade',
    country: 'Serbia',
    salary: '€2,000 - €3,000/month',
    experience: '3-6 years',
    contractDuration: '24 months',
    description: 'Seeking an experienced Business Development Manager to drive growth and establish partnerships in the Balkan region.',
    responsibilities: [
      'Identify and pursue new business opportunities',
      'Build and maintain client relationships',
      'Develop strategic partnerships',
      'Create and present business proposals',
      'Meet sales targets and KPIs',
    ],
    requirements: [
      'Bachelor\'s degree in Business or related field',
      '3+ years in business development or sales',
      'Excellent communication and negotiation skills',
      'Proven track record of meeting targets',
      'Fluent in English',
    ],
    skills: ['Sales', 'Negotiation', 'CRM', 'Market Analysis', 'Communication'],
    benefits: ['Commission structure', 'Company car', 'Health insurance', 'Travel opportunities'],
    postedDate: '2024-11-28',
  },
  {
    id: '3',
    title: 'Project Manager',
    company: 'Construction Pro Bulgaria',
    companyType: 'Construction',
    location: 'Plovdiv',
    country: 'Bulgaria',
    salary: '€2,800 - €3,800/month',
    experience: '5-8 years',
    contractDuration: '36 months',
    description: 'Lead construction projects from planning to completion for residential and commercial developments.',
    responsibilities: [
      'Plan and oversee construction projects',
      'Manage project budgets and timelines',
      'Coordinate with contractors and suppliers',
      'Ensure compliance with safety regulations',
      'Prepare project reports',
    ],
    requirements: [
      'Degree in Civil Engineering or Construction Management',
      '5+ years of project management experience',
      'PMP or PRINCE2 certification preferred',
      'Strong leadership skills',
      'Knowledge of construction regulations',
    ],
    skills: ['Project Management', 'Budgeting', 'AutoCAD', 'MS Project', 'Leadership'],
    benefits: ['Performance bonuses', 'Company housing', 'Health insurance', 'Career growth'],
    postedDate: '2024-11-25',
  },
  {
    id: '4',
    title: 'Marketing Specialist',
    company: 'Digital Wave Serbia',
    companyType: 'Marketing',
    location: 'Novi Sad',
    country: 'Serbia',
    salary: '€1,800 - €2,500/month',
    experience: '2-4 years',
    contractDuration: '24 months',
    description: 'Creative marketing professional needed to develop and execute digital marketing campaigns.',
    responsibilities: [
      'Develop and implement marketing strategies',
      'Manage social media accounts',
      'Create engaging content',
      'Analyze campaign performance',
      'Collaborate with design team',
    ],
    requirements: [
      'Bachelor\'s degree in Marketing or related field',
      '2+ years of digital marketing experience',
      'Proficiency in Google Analytics and social media platforms',
      'Strong writing and communication skills',
      'Creative thinking',
    ],
    skills: ['Digital Marketing', 'SEO', 'Content Creation', 'Analytics', 'Social Media'],
    benefits: ['Creative environment', 'Training programs', 'Flexible schedule', 'Team events'],
    postedDate: '2024-11-30',
  },
  {
    id: '5',
    title: 'Financial Analyst',
    company: 'Finance Group Bulgaria',
    companyType: 'Finance',
    location: 'Sofia',
    country: 'Bulgaria',
    salary: '€2,200 - €3,200/month',
    experience: '3-5 years',
    contractDuration: '24 months',
    description: 'Analyze financial data and provide insights to support business decisions in a growing financial services firm.',
    responsibilities: [
      'Prepare financial reports and forecasts',
      'Analyze financial performance',
      'Develop financial models',
      'Support budgeting processes',
      'Present findings to management',
    ],
    requirements: [
      'Bachelor\'s degree in Finance, Accounting, or Economics',
      '3+ years of financial analysis experience',
      'Advanced Excel skills',
      'CFA or similar certification preferred',
      'Attention to detail',
    ],
    skills: ['Financial Analysis', 'Excel', 'SAP', 'Data Visualization', 'Reporting'],
    benefits: ['Competitive salary', 'Bonus scheme', 'Professional certification support', 'Modern office'],
    postedDate: '2024-12-02',
  },
  {
    id: '6',
    title: 'HR Manager',
    company: 'People First Serbia',
    companyType: 'Human Resources',
    location: 'Belgrade',
    country: 'Serbia',
    salary: '€2,000 - €2,800/month',
    experience: '4-7 years',
    contractDuration: '24 months',
    description: 'Lead HR operations and talent acquisition for a fast-growing organization with multinational teams.',
    responsibilities: [
      'Develop HR strategies and policies',
      'Manage recruitment processes',
      'Handle employee relations',
      'Oversee performance management',
      'Ensure compliance with labor laws',
    ],
    requirements: [
      'Bachelor\'s degree in HR or related field',
      '4+ years of HR management experience',
      'Knowledge of Serbian labor law',
      'SHRM or CIPD certification preferred',
      'Strong interpersonal skills',
    ],
    skills: ['HR Management', 'Recruitment', 'Employee Relations', 'HRIS', 'Training'],
    benefits: ['Work-life balance', 'Professional development', 'Health benefits', 'International exposure'],
    postedDate: '2024-11-27',
  },
  {
    id: '7',
    title: 'Quality Assurance Engineer',
    company: 'Software Labs Bulgaria',
    companyType: 'Technology',
    location: 'Varna',
    country: 'Bulgaria',
    salary: '€2,300 - €3,000/month',
    experience: '2-5 years',
    contractDuration: '24 months',
    description: 'Ensure software quality through comprehensive testing for enterprise applications.',
    responsibilities: [
      'Design and execute test cases',
      'Perform manual and automated testing',
      'Report and track bugs',
      'Collaborate with development team',
      'Improve QA processes',
    ],
    requirements: [
      'Bachelor\'s degree in Computer Science or related field',
      '2+ years of QA experience',
      'Experience with testing frameworks (Selenium, Jest)',
      'Understanding of CI/CD pipelines',
      'Detail-oriented mindset',
    ],
    skills: ['Test Automation', 'Selenium', 'JIRA', 'API Testing', 'Agile'],
    benefits: ['Remote work options', 'Learning budget', 'Modern tech stack', 'Team building'],
    postedDate: '2024-12-03',
  },
  {
    id: '8',
    title: 'Mechanical Engineer',
    company: 'Industrial Solutions Serbia',
    companyType: 'Manufacturing',
    location: 'Nis',
    country: 'Serbia',
    salary: '€2,100 - €2,900/month',
    experience: '3-6 years',
    contractDuration: '36 months',
    description: 'Design and optimize mechanical systems for industrial manufacturing processes.',
    responsibilities: [
      'Design mechanical components and systems',
      'Conduct technical calculations',
      'Oversee manufacturing processes',
      'Troubleshoot mechanical issues',
      'Collaborate with production team',
    ],
    requirements: [
      'Bachelor\'s degree in Mechanical Engineering',
      '3+ years of industry experience',
      'Proficiency in CAD software (SolidWorks, AutoCAD)',
      'Knowledge of manufacturing processes',
      'Strong analytical skills',
    ],
    skills: ['Mechanical Design', 'CAD', 'SolidWorks', 'Manufacturing', 'Problem Solving'],
    benefits: ['Technical training', 'Career progression', 'Health insurance', 'Relocation package'],
    postedDate: '2024-11-26',
  },
  {
    id: '9',
    title: 'Customer Success Manager',
    company: 'SaaS Innovators Bulgaria',
    companyType: 'Technology',
    location: 'Sofia',
    country: 'Bulgaria',
    salary: '€2,400 - €3,200/month',
    experience: '3-5 years',
    contractDuration: '24 months',
    description: 'Build lasting relationships with clients and ensure their success with our SaaS platform.',
    responsibilities: [
      'Onboard new customers',
      'Provide ongoing support and training',
      'Monitor customer health metrics',
      'Identify upsell opportunities',
      'Gather customer feedback',
    ],
    requirements: [
      'Bachelor\'s degree in Business or related field',
      '3+ years in customer success or account management',
      'Experience with SaaS products',
      'Excellent communication skills',
      'Customer-centric mindset',
    ],
    skills: ['Customer Success', 'CRM', 'Communication', 'Data Analysis', 'Presentation'],
    benefits: ['Stock options', 'Professional growth', 'International team', 'Flexible hours'],
    postedDate: '2024-12-04',
  },
  {
    id: '10',
    title: 'Electrical Engineer',
    company: 'Energy Systems Serbia',
    companyType: 'Energy',
    location: 'Belgrade',
    country: 'Serbia',
    salary: '€2,600 - €3,400/month',
    experience: '4-7 years',
    contractDuration: '36 months',
    description: 'Design and maintain electrical systems for renewable energy projects across the Balkans.',
    responsibilities: [
      'Design electrical systems and circuits',
      'Perform system testing and commissioning',
      'Ensure compliance with electrical codes',
      'Prepare technical documentation',
      'Supervise installation teams',
    ],
    requirements: [
      'Bachelor\'s degree in Electrical Engineering',
      '4+ years of relevant experience',
      'Knowledge of renewable energy systems',
      'Professional engineering license preferred',
      'Strong technical skills',
    ],
    skills: ['Electrical Design', 'AutoCAD Electrical', 'PLC', 'Power Systems', 'Troubleshooting'],
    benefits: ['Competitive package', 'Project bonuses', 'International projects', 'Technical development'],
    postedDate: '2024-11-29',
  },
  {
    id: '11',
    title: 'Data Analyst',
    company: 'Analytics Hub Bulgaria',
    companyType: 'Technology',
    location: 'Sofia',
    country: 'Bulgaria',
    salary: '€2,100 - €2,800/month',
    experience: '2-4 years',
    contractDuration: '24 months',
    description: 'Transform data into actionable insights for business intelligence and decision-making.',
    responsibilities: [
      'Collect and analyze business data',
      'Create dashboards and visualizations',
      'Generate reports for stakeholders',
      'Identify trends and patterns',
      'Support data-driven decision making',
    ],
    requirements: [
      'Bachelor\'s degree in Statistics, Mathematics, or related field',
      '2+ years of data analysis experience',
      'Proficiency in SQL and Excel',
      'Experience with BI tools (Tableau, Power BI)',
      'Strong analytical thinking',
    ],
    skills: ['Data Analysis', 'SQL', 'Python', 'Tableau', 'Statistics'],
    benefits: ['Learning opportunities', 'Modern tools', 'Collaborative environment', 'Career growth'],
    postedDate: '2024-12-05',
  },
  {
    id: '12',
    title: 'Operations Manager',
    company: 'Logistics Plus Serbia',
    companyType: 'Logistics',
    location: 'Belgrade',
    country: 'Serbia',
    salary: '€2,500 - €3,300/month',
    experience: '5-8 years',
    contractDuration: '24 months',
    description: 'Oversee daily operations and optimize supply chain processes for regional distribution center.',
    responsibilities: [
      'Manage warehouse and logistics operations',
      'Optimize operational processes',
      'Lead operations team',
      'Monitor KPIs and performance metrics',
      'Implement efficiency improvements',
    ],
    requirements: [
      'Bachelor\'s degree in Business or Supply Chain Management',
      '5+ years of operations management experience',
      'Knowledge of logistics software',
      'Strong leadership abilities',
      'Lean Six Sigma certification preferred',
    ],
    skills: ['Operations Management', 'Supply Chain', 'Leadership', 'Process Optimization', 'SAP'],
    benefits: ['Performance incentives', 'Leadership training', 'Health benefits', 'Career advancement'],
    postedDate: '2024-11-24',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: '1',
    name: 'Ahmed Hassan',
    role: 'Software Developer',
    company: 'Tech Solutions Bulgaria',
    country: 'UAE → Bulgaria',
    quote: 'Hype Wave made my relocation from Dubai to Sofia seamless. The team handled everything from visa processing to finding accommodation. I\'m now thriving in my new role!',
    type: 'candidate',
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Marketing Manager',
    company: 'Digital Wave Serbia',
    country: 'India → Serbia',
    quote: 'The entire process was transparent and professional. They guided me through every step and I felt supported throughout my journey to Belgrade. Highly recommended!',
    type: 'candidate',
  },
  {
    id: '3',
    name: 'Muhammad Ali',
    role: 'Project Manager',
    company: 'Construction Pro Bulgaria',
    country: 'Pakistan → Bulgaria',
    quote: 'Working with Hype Wave was the best decision I made for my career. They matched me with the perfect job opportunity and made the transition stress-free.',
    type: 'candidate',
  },
  {
    id: '4',
    name: 'Fatima Khan',
    role: 'Financial Analyst',
    company: 'Finance Group Bulgaria',
    country: 'UAE → Bulgaria',
    quote: 'I was nervous about relocating to Europe, but Hype Wave\'s support gave me confidence. From interview prep to arrival assistance, they were there every step of the way.',
    type: 'candidate',
  },
  {
    id: '5',
    name: 'Raj Patel',
    role: 'Business Development',
    company: 'Global Trade Serbia',
    country: 'India → Serbia',
    quote: 'Exceptional service! The team understood my career goals and found opportunities that aligned perfectly. My move to Serbia has opened up amazing possibilities.',
    type: 'candidate',
  },
  {
    id: '6',
    name: 'Tech Solutions Bulgaria',
    role: 'HR Director',
    country: 'Bulgaria',
    quote: 'Hype Wave consistently delivers high-quality candidates who integrate seamlessly into our teams. Their screening process is thorough and professional.',
    type: 'company',
  },
  {
    id: '7',
    name: 'Digital Wave Serbia',
    role: 'CEO',
    country: 'Serbia',
    quote: 'We\'ve hired multiple professionals through Hype Wave. They understand our needs and always present candidates who meet our requirements. A trusted recruitment partner.',
    type: 'company',
  },
  {
    id: '8',
    name: 'Finance Group Bulgaria',
    role: 'Managing Partner',
    country: 'Bulgaria',
    quote: 'The caliber of talent Hype Wave brings is outstanding. They handle all the complex visa and relocation processes, allowing us to focus on integration and onboarding.',
    type: 'company',
  },
];

export const features = [
  {
    id: '1',
    title: 'No Hassle Process',
    description: 'We handle all paperwork, visa applications, and bureaucratic requirements so you can focus on your career.',
    icon: 'CheckCircle',
  },
  {
    id: '2',
    title: 'Verified Employers',
    description: 'Work with trusted companies across Bulgaria and Serbia. All our partner employers are thoroughly vetted.',
    icon: 'Shield',
  },
  {
    id: '3',
    title: 'Smooth Visa Process',
    description: 'Expert guidance through work permits and visa applications with high success rates.',
    icon: 'FileCheck',
  },
  {
    id: '4',
    title: 'End-to-End Support',
    description: 'From eligibility check to arrival assistance, we support you throughout your relocation journey.',
    icon: 'HeartHandshake',
  },
];

export const processSteps = [
  {
    id: 1,
    title: 'Confirm Eligibility',
    description: 'Complete our quick eligibility assessment to determine if you qualify for work opportunities in Bulgaria or Serbia.',
    icon: 'ClipboardCheck',
  },
  {
    id: 2,
    title: 'Sign Contract',
    description: 'Review and sign your employment contract with verified employers across Bulgaria and Serbia.',
    icon: 'FileText',
  },
  {
    id: 3,
    title: 'Job Interview',
    description: 'Connect with potential employers through interviews arranged by our team. We provide preparation support.',
    icon: 'Video',
  },
  {
    id: 4,
    title: 'Work Permit',
    description: 'We facilitate your work permit application process with full documentation support.',
    icon: 'Briefcase',
  },
  {
    id: 5,
    title: 'Visa Application',
    description: 'Our experts guide you through visa requirements and documentation for a smooth approval process.',
    icon: 'Passport',
  },
  {
    id: 6,
    title: 'Relocate',
    description: 'Get assistance with travel arrangements, accommodation, and settling into your new home and workplace.',
    icon: 'Plane',
  },
];
